name: Docker dev image

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file dockerfile.dev --tag ashishbadgujardocker124/docker-react

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run the docker image
        run: docker run ashishbadgujardocker124/docker-react npm run test
