name: Docker build test

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . -f Dockerfile.dev --tag dkrashi/docker-react
      - name: run the docker image
        run: docker run dkrashi/docker-react npm test -- --coverage

        
