name: Docker dev image

on:
  push:
    branches: [feature]
  pull_request:
    branches: [feature]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file dockerfile.dev --tag my-image-name:docker-react

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker run ashishbadgujardocker124/docker-react npm run test -- --coverage
