name: run unit test

on:
  push:
    branches: [feature]
  pull_request:
    branches: [feature]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: npm run test
